apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    gpu: "true"
    app: jetson-stats-exporter
  name: jetson-stats-exporter
  namespace: monitoring
spec:
  selector:
    matchLabels:
      gpu: "true"
      app: jetson-stats-exporter
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
      labels:
        gpu: "true"
        app: jetson-stats-exporter
    spec:
      imagePullSecrets:
        - name: dockerconfigjson-github-com
      nodeSelector:
        gpu: "true"
      containers:
      - command: ["python", "__main__.py"] 
        args:
        - --port=9400
        image: ghcr.io/hari5g900/jetson_stats_exporter:latest
        imagePullPolicy: IfNotPresent
        name: jetson-stats-exporter
        ports:
        - containerPort: 9400
          hostPort: 9400
          name: metrics
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 30Mi
        volumeMounts:
        # - mountPath: /host/proc
        #   name: proc
        #   readOnly: true
        # - mountPath: /host/sys
        #   name: sys
        #   readOnly: true
        - mountPath: /host/run/jtop.sock
          name: run/jtop.sock
          readOnly: false
      hostPID: true
      restartPolicy: Always
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
      volumes:
      # - hostPath:
      #     path: /proc
      #     type: ""
      #   name: proc
      # - hostPath:
      #     path: /sys
      #     type: ""
      #   name: sys
      - hostPath:
          path: /run
          type: ""
        name: run/jtop.sock
---
apiVersion: v1
kind: Service
metadata:
  labels:
    gpu: "true"
    app: jetson-stats-exporter
  name: jetson-stats-exporter
  namespace: monitoring
spec:
  ports:
  - name: jetson-stats-exporter
    port: 9400
    protocol: TCP
    targetPort: 9400
  selector:
    app: jetson-stats-exporter
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    gpu: "true"
    app: jetson-stats-exporter
    serviceMonitorSelector: prometheus
  name: jetson-stats-exporter
  namespace: monitoring
spec:
  endpoints:
  - honorLabels: true
    interval: 30s
    path: /metrics
    targetPort: 9400
  jobLabel: jetson-stats-exporter
  namespaceSelector:
    matchNames:
    - prometheus
  selector:
    matchLabels:
      gpu: "true"
      app: jetson-stats-exporter